const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const passportLocalMongoose = require("passport-local-mongoose");

//we haven't defined username, password as it is automatically generated by the "passport-local-mongoose" package
const userSchema = new Schema({ 
    email : {
        type : String,
        required : true,
    }
});

userSchema.plugin(passportLocalMongoose); 

module.exports = mongoose.model("User", userSchema);